### ISSUE TITLE
[Feature Request] Report only shows battery and firmware, not saved settings

### ISSUE THREAD

**Issue by cglmrfreeman** [korkje/mow#8]
While I haven't used the Glorious program to view settings on a Windows machine, I assume the program shows you what the current settings of the mouse are so you can alter them. Such as what color settings you have, which DPI settings you are on, what your DPI stages are set to, and even your polling rate.

While it's understandable that you can just set them to what you want, overwriting the setting even if it is the same, it would be nice to see what your configurations are in case you forget which specific setting (especially color codes) you liked so you can use them again in the next configuration you set.

**Comment by korkje** [comment]
Hi! I originally intended to include this functionality, but unfortunately the device does not support reading any information about it other than firmware verison and battery percentage.

The way this works in Glorious Core (on Windows) is that the application at all times keeps a local state of all device settings, and actually writes all of it to the device upon connecting it. So while this gives the appearance of being able to read settings, that's not really what it does. E.g. if you were to use a device with separate Windows machines (and thus different Glorious Core installations) the configuration you do on one machine would not be persisted when connecting to the other one.

I thought about doing something similar with this program, i.e. keeping a copy of configuration locally, but that would require a few things. First, the additional code required to keep this local config up to date. Second, writing the config to the device upon connection (which in turn would require mow to be daemonized), if we don't do this, the config cannot really be "trusted" in some sense, as the device could have been configured on another machine.

So at least for the time being, I just kept it as simple as possible, so that you can configure the device on another machine if you want, while still being able to do adjustments on the fly with mow.

**Comment by korkje** [comment]
So while I will not be able to report config directly from the device, I have been thinking I might add functionality to read config files (in the same format that can be exported from glorious core) and write them to the device in one go (e.g. `mow config ingest my_device_profile.json`). Not really what you're asking for, but maybe that would be helpful in some sense, as it would allow for keeping settings more easily (though still somewhat of a pain) up to date between machines at least.

**Comment by korkje** [comment]
...or, and this is only if I suddenly get a whole lot of time on my hands, I could reverse engineer the device firmware and create some kind of jailbreak version that would allow for reading config from the device. I have thought about this, and it would be a fun project, but I simply cannot justify prioritizing it for the time being.

**Comment by cglmrfreeman** [comment]
Booo to devs who do this to their firmwares BOOOOOOOO!

Thank you very much for clearly explaining the situation. Your development on this app has been most appreciated! :smile:
